/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JOptionPane;
import DAL.KhachHang;

/**
 *
 * @author thaotruogg
 */
public class JFrame_Input_Guest extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Input_Guest
     */
    public JFrame_Input_Guest() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCloseGuest = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtNoCK = new javax.swing.JTextField();
        jtxtGuestName = new javax.swing.JTextField();
        jtxtGuestAddress = new javax.swing.JTextField();
        jtxtGuestPhone = new javax.swing.JTextField();
        jtxtNoDK = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtxtGuestId = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(410, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 0, 87));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("KHÁCH HÀNG");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 0, 123, 40));

        btnCloseGuest.setBackground(new java.awt.Color(245, 0, 87));
        btnCloseGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseGuestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseGuestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseGuestMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCloseGuestMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCloseGuestMouseReleased(evt);
            }
        });
        btnCloseGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\close_16px.png")); // NOI18N
        btnCloseGuest.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel1.add(btnCloseGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 408, 40));

        jPanel3.setBackground(new java.awt.Color(252, 228, 236));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel3.setText("VNĐ");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 30, -1));

        jLabel4.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel4.setText("Tên khách hàng");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, -1));

        jLabel5.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel5.setText("Địa chỉ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 90, -1));

        jLabel6.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel6.setText("Số điện thoại");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, -1));

        jLabel7.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel7.setText("Nợ đầu kì");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 90, -1));

        jtxtNoCK.setBackground(new java.awt.Color(252, 228, 236));
        jtxtNoCK.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtNoCK.setText("10000000");
        jtxtNoCK.setBorder(null);
        jtxtNoCK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNoCKMouseClicked(evt);
            }
        });
        jPanel3.add(jtxtNoCK, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 200, 30));

        jtxtGuestName.setBackground(new java.awt.Color(252, 228, 236));
        jtxtGuestName.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtGuestName.setText("Nhập tên khách hàng");
        jtxtGuestName.setBorder(null);
        jtxtGuestName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtGuestNameMouseClicked(evt);
            }
        });
        jPanel3.add(jtxtGuestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 240, 30));

        jtxtGuestAddress.setBackground(new java.awt.Color(252, 228, 236));
        jtxtGuestAddress.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtGuestAddress.setText("Nhập địa chỉ");
        jtxtGuestAddress.setBorder(null);
        jtxtGuestAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtGuestAddressMouseClicked(evt);
            }
        });
        jPanel3.add(jtxtGuestAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 240, 30));

        jtxtGuestPhone.setBackground(new java.awt.Color(252, 228, 236));
        jtxtGuestPhone.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtGuestPhone.setText("Nhập số điện thoại");
        jtxtGuestPhone.setBorder(null);
        jtxtGuestPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtGuestPhoneMouseClicked(evt);
            }
        });
        jPanel3.add(jtxtGuestPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 240, 30));

        jtxtNoDK.setBackground(new java.awt.Color(252, 228, 236));
        jtxtNoDK.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtNoDK.setText("10000000");
        jtxtNoDK.setBorder(null);
        jtxtNoDK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNoDKMouseClicked(evt);
            }
        });
        jtxtNoDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNoDKActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtNoDK, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 200, 30));

        jButtonSave.setBackground(new java.awt.Color(255, 64, 129));
        jButtonSave.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jButtonSave.setText("LƯU");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 80, 40));

        jLabel8.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel8.setText("Mã khách hàng");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 90, -1));

        jtxtGuestId.setBackground(new java.awt.Color(252, 228, 236));
        jtxtGuestId.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtGuestId.setText("Nhập mã khách hàng");
        jtxtGuestId.setBorder(null);
        jtxtGuestId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtGuestIdMouseClicked(evt);
            }
        });
        jtxtGuestId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGuestIdActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtGuestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 240, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 200, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 240, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 240, 10));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 240, 10));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 240, 10));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 200, 10));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 240, 10));

        jLabel9.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel9.setText("Nợ cuối kì");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 90, -1));

        jLabel10.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel10.setText("VNĐ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 30, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 40, 408, 459));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        checkField();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jtxtGuestIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGuestIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGuestIdActionPerformed

    private void jtxtNoDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNoDKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNoDKActionPerformed

    private void btnCloseGuestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseGuestMouseEntered
        btnCloseGuest.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_btnCloseGuestMouseEntered

    private void btnCloseGuestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseGuestMouseExited
        btnCloseGuest.setBackground(new Color(245,0,87));
    }//GEN-LAST:event_btnCloseGuestMouseExited

    private void btnCloseGuestMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseGuestMousePressed
        btnCloseGuest.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_btnCloseGuestMousePressed

    private void btnCloseGuestMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseGuestMouseReleased
        btnCloseGuest.setBackground(new Color(245,0,87));
    }//GEN-LAST:event_btnCloseGuestMouseReleased

    private void btnCloseGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseGuestMouseClicked
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseGuestMouseClicked

    private void jtxtGuestIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtGuestIdMouseClicked
        jtxtGuestId.setText(null);
    }//GEN-LAST:event_jtxtGuestIdMouseClicked

    private void jtxtGuestNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtGuestNameMouseClicked
        jtxtGuestName.setText(null);
    }//GEN-LAST:event_jtxtGuestNameMouseClicked

    private void jtxtGuestAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtGuestAddressMouseClicked
        jtxtGuestAddress.setText(null);
    }//GEN-LAST:event_jtxtGuestAddressMouseClicked

    private void jtxtGuestPhoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtGuestPhoneMouseClicked
        jtxtGuestPhone.setText(null);
    }//GEN-LAST:event_jtxtGuestPhoneMouseClicked

    private void jtxtNoDKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNoDKMouseClicked
        jtxtNoDK.setText(null);
    }//GEN-LAST:event_jtxtNoDKMouseClicked

    private void jtxtNoCKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNoCKMouseClicked
        jtxtNoCK.setText(null);
    }//GEN-LAST:event_jtxtNoCKMouseClicked

    public void checkField(){
//        float noDK = Float.parseFloat(jtxtNoDK.getText());
//        float noCK = Float.parseFloat(jtxtNoDK.getText());
//        if(jtxtGuestId.getText().length() == 0 || jtxtGuestName.getText().length() == 0 || jtxtGuestPhone.getText().length() == 0 || jtxtNoDK.getText().length() == 0 || jtxtNoCK.getText().length() == 0){
//            JOptionPane.showMessageDialog(null, "Chỉ cho phép bỏ qua trường địa chỉ", "Thông báo lỗi", 1);
//        }
//        else{
//            KhachHang.InsertKhachHang(jtxtGuestId.getText(), jtxtGuestName.getText(), jtxtGuestPhone.getText(), jtxtGuestAddress.getText(), noDK, noCK);
//            dispose();
//        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Input_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Input_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Input_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Input_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Input_Guest().setVisible(true);
            }
        });
    }
    
    int xx, xy;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCloseGuest;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jtxtGuestAddress;
    private javax.swing.JTextField jtxtGuestId;
    private javax.swing.JTextField jtxtGuestName;
    private javax.swing.JTextField jtxtGuestPhone;
    private javax.swing.JTextField jtxtNoCK;
    private javax.swing.JTextField jtxtNoDK;
    // End of variables declaration//GEN-END:variables
}
