/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author thaotruogg
 */
public class JFrame_Bill extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Bill
     */
    public JFrame_Bill() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCloseBill = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtGuestName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtxtGuestId = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(410, 359));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 0, 87));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HÓA ĐƠN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 0, 123, 40));

        btnCloseBill.setBackground(new java.awt.Color(245, 0, 87));
        btnCloseBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseBillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseBillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseBillMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCloseBillMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCloseBillMouseReleased(evt);
            }
        });
        btnCloseBill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\close_16px.png")); // NOI18N
        btnCloseBill.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel1.add(btnCloseBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 408, 40));

        jPanel3.setBackground(new java.awt.Color(252, 228, 236));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel4.setText("Mã khách hàng");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, -1));

        jLabel5.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel5.setText("Ngày lập hóa đơn");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 100, -1));

        jtxtGuestName.setBackground(new java.awt.Color(252, 228, 236));
        jtxtGuestName.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtGuestName.setText("Nhập mã khách hàng");
        jtxtGuestName.setBorder(null);
        jtxtGuestName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtGuestNameMouseClicked(evt);
            }
        });
        jPanel3.add(jtxtGuestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 240, 30));

        jButton1.setBackground(new java.awt.Color(255, 64, 129));
        jButton1.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LƯU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 80, 40));

        jLabel8.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel8.setText("Số hóa đơn");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 90, -1));

        jtxtGuestId.setBackground(new java.awt.Color(252, 228, 236));
        jtxtGuestId.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtGuestId.setText("Nhập số hóa đơn");
        jtxtGuestId.setBorder(null);
        jtxtGuestId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtGuestIdMouseClicked(evt);
            }
        });
        jtxtGuestId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGuestIdActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtGuestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 240, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 240, 10));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 240, 10));

        dateChooserCombo2.setCalendarPreferredSize(new java.awt.Dimension(350, 280));
        dateChooserCombo2.setFieldFont(new java.awt.Font("Nunito", java.awt.Font.PLAIN, 12));
        dateChooserCombo2.setLocale(new java.util.Locale("vi", "", ""));
        dateChooserCombo2.setNavigateFont(new java.awt.Font("Nunito", java.awt.Font.PLAIN, 12));
        dateChooserCombo2.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);
        jPanel3.add(dateChooserCombo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 240, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 40, 408, 318));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseBillMouseClicked
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseBillMouseClicked

    private void btnCloseBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseBillMouseEntered
        btnCloseBill.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_btnCloseBillMouseEntered

    private void btnCloseBillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseBillMouseExited
        btnCloseBill.setBackground(new Color(245,0,87));
    }//GEN-LAST:event_btnCloseBillMouseExited

    private void btnCloseBillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseBillMousePressed
        btnCloseBill.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_btnCloseBillMousePressed

    private void btnCloseBillMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseBillMouseReleased
        btnCloseBill.setBackground(new Color(245,0,87));
    }//GEN-LAST:event_btnCloseBillMouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jtxtGuestNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtGuestNameMouseClicked
        jtxtGuestName.setText(null);
    }//GEN-LAST:event_jtxtGuestNameMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtGuestIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtGuestIdMouseClicked
        jtxtGuestId.setText(null);
    }//GEN-LAST:event_jtxtGuestIdMouseClicked

    private void jtxtGuestIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGuestIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGuestIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Bill().setVisible(true);
            }
        });
    }

    int xx, xy;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCloseBill;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jtxtGuestId;
    private javax.swing.JTextField jtxtGuestName;
    // End of variables declaration//GEN-END:variables
}
