/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author thaotruogg
 */
public class JFrameCategory extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCategory
     */
    public JFrameCategory() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCloseCategory = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableCategories = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxtNameCategory = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jtxtSearchCategories = new javax.swing.JTextField();
        btnSearchCategories = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jbtnAddCategory = new javax.swing.JButton();
        jbtnDeleteCategory = new javax.swing.JButton();
        jbtnEditCategory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(552, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 230, 118));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ LOẠI VẬT LIỆU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, 40));

        btnCloseCategory.setBackground(new java.awt.Color(0, 230, 118));
        btnCloseCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseCategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseCategoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCloseCategoryMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCloseCategoryMouseReleased(evt);
            }
        });
        btnCloseCategory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\close_16px.png")); // NOI18N
        btnCloseCategory.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel1.add(btnCloseCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 550, 40));

        jPanel2.setBackground(new java.awt.Color(232, 245, 233));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtableCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã loại sản phẩm", "Tên loại sản phẩm"
            }
        ));
        jtableCategories.setGridColor(new java.awt.Color(232, 245, 233));
        jtableCategories.setRowHeight(24);
        jScrollPane1.setViewportView(jtableCategories);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 340));

        jPanel3.setBackground(new java.awt.Color(232, 245, 233));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel3.setText("Tên loại vật liệu");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, -1, -1));

        jtxtNameCategory.setBackground(new java.awt.Color(232, 245, 233));
        jtxtNameCategory.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtNameCategory.setText("Nhập tên loại vật liệu");
        jtxtNameCategory.setBorder(null);
        jtxtNameCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNameCategoryMouseClicked(evt);
            }
        });
        jPanel3.add(jtxtNameCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 200, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 10));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 250, 90));

        jPanel4.setBackground(new java.awt.Color(232, 245, 233));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtSearchCategories.setBackground(new java.awt.Color(232, 245, 233));
        jtxtSearchCategories.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtSearchCategories.setText("Nhập tên loại tìm kiếm");
        jtxtSearchCategories.setBorder(null);
        jtxtSearchCategories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSearchCategoriesMouseClicked(evt);
            }
        });
        jPanel4.add(jtxtSearchCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 30));

        btnSearchCategories.setBackground(new java.awt.Color(244, 67, 54));
        btnSearchCategories.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        btnSearchCategories.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchCategories.setText("Tìm kiếm");
        jPanel4.add(btnSearchCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 10));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 250, 70));

        jbtnAddCategory.setBackground(new java.awt.Color(0, 230, 118));
        jbtnAddCategory.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\add_24px.png")); // NOI18N
        jPanel2.add(jbtnAddCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jbtnDeleteCategory.setBackground(new java.awt.Color(244, 67, 54));
        jbtnDeleteCategory.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\delete_24px.png")); // NOI18N
        jPanel2.add(jbtnDeleteCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        jbtnEditCategory.setBackground(new java.awt.Color(0, 230, 118));
        jbtnEditCategory.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\edit_property_24px.png")); // NOI18N
        jPanel2.add(jbtnEditCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 40, 550, 358));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btnCloseCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseCategoryMouseEntered
        setColorRed(btnCloseCategory);
    }//GEN-LAST:event_btnCloseCategoryMouseEntered

    private void btnCloseCategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseCategoryMouseExited
        resetColor(btnCloseCategory);
    }//GEN-LAST:event_btnCloseCategoryMouseExited

    private void btnCloseCategoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseCategoryMousePressed
        setColorDeep(btnCloseCategory);
    }//GEN-LAST:event_btnCloseCategoryMousePressed

    private void btnCloseCategoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseCategoryMouseReleased
        resetColor(btnCloseCategory);
    }//GEN-LAST:event_btnCloseCategoryMouseReleased

    private void btnCloseCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseCategoryMouseClicked
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseCategoryMouseClicked

    private void jtxtSearchCategoriesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSearchCategoriesMouseClicked
        jtxtSearchCategories.setText(null);
    }//GEN-LAST:event_jtxtSearchCategoriesMouseClicked

    private void jtxtNameCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNameCategoryMouseClicked
        jtxtNameCategory.setText(null);
    }//GEN-LAST:event_jtxtNameCategoryMouseClicked

    void setColorRed(JPanel jp){
        jp.setBackground(new Color(244, 67, 54));
    }
    
    void resetColor(JPanel jp){
        jp.setBackground(new Color(0, 230, 118));
    }
    void setColorDeep(JPanel jp){
        jp.setBackground(new Color(67, 160, 71));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCategory().setVisible(true);
            }
        });
    }
    
    int xx, xy;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCloseCategory;
    private javax.swing.JButton btnSearchCategories;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnAddCategory;
    private javax.swing.JButton jbtnDeleteCategory;
    private javax.swing.JButton jbtnEditCategory;
    private javax.swing.JTable jtableCategories;
    private javax.swing.JTextField jtxtNameCategory;
    private javax.swing.JTextField jtxtSearchCategories;
    // End of variables declaration//GEN-END:variables
}
