/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;

/**
 *
 * @author thaotruogg
 */
public class JFrame_Sub_Bill extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Sub_Bill
     */
    public JFrame_Sub_Bill() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCloseSubBill = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtxtGuestId = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jtxtGuestName1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jtxtGuestName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(410, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 0, 87));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HÓA ĐƠN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 0, 123, 40));

        btnCloseSubBill.setBackground(new java.awt.Color(245, 0, 87));
        btnCloseSubBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseSubBillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseSubBillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseSubBillMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCloseSubBillMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCloseSubBillMouseReleased(evt);
            }
        });
        btnCloseSubBill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\close_16px.png")); // NOI18N
        btnCloseSubBill.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel1.add(btnCloseSubBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 408, 40));

        jPanel2.setBackground(new java.awt.Color(252, 228, 236));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 64, 129));
        jButton1.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jButton1.setText("LƯU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 80, 40));

        jLabel8.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel8.setText("Số hóa đơn");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 90, -1));

        jtxtGuestId.setBackground(new java.awt.Color(252, 228, 236));
        jtxtGuestId.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtGuestId.setText("Nhập số hóa đơn");
        jtxtGuestId.setBorder(null);
        jtxtGuestId.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtGuestIdMouseClicked(evt);
            }
        });
        jtxtGuestId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtGuestIdActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtGuestId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 240, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 240, 10));

        jLabel7.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel7.setText("Đơn giá");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 100, -1));

        jtxtGuestName1.setBackground(new java.awt.Color(252, 228, 236));
        jtxtGuestName1.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtGuestName1.setText("10000000");
        jtxtGuestName1.setBorder(null);
        jtxtGuestName1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtGuestName1MouseClicked(evt);
            }
        });
        jPanel2.add(jtxtGuestName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 200, 30));

        jLabel6.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel6.setText("Số lượng");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 100, -1));

        jLabel5.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel5.setText("VNĐ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 40, -1));

        jSpinner1.setBorder(null);
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 110, 30));

        jtxtGuestName.setBackground(new java.awt.Color(252, 228, 236));
        jtxtGuestName.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtGuestName.setText("Nhập mã khách hàng");
        jtxtGuestName.setBorder(null);
        jtxtGuestName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtGuestNameMouseClicked(evt);
            }
        });
        jPanel2.add(jtxtGuestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 240, 30));

        jLabel4.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel4.setText("Mã sản phẩm");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 240, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 409, 319));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseSubBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSubBillMouseClicked
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseSubBillMouseClicked

    private void btnCloseSubBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSubBillMouseEntered
        btnCloseSubBill.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_btnCloseSubBillMouseEntered

    private void btnCloseSubBillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSubBillMouseExited
        btnCloseSubBill.setBackground(new Color(245,0,87));
    }//GEN-LAST:event_btnCloseSubBillMouseExited

    private void btnCloseSubBillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSubBillMousePressed
        btnCloseSubBill.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_btnCloseSubBillMousePressed

    private void btnCloseSubBillMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSubBillMouseReleased
        btnCloseSubBill.setBackground(new Color(245,0,87));
    }//GEN-LAST:event_btnCloseSubBillMouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtxtGuestIdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtGuestIdMouseClicked
        jtxtGuestId.setText(null);
    }//GEN-LAST:event_jtxtGuestIdMouseClicked

    private void jtxtGuestIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtGuestIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGuestIdActionPerformed

    private void jtxtGuestName1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtGuestName1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtGuestName1MouseClicked

    private void jtxtGuestNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtGuestNameMouseClicked
        jtxtGuestName.setText(null);
    }//GEN-LAST:event_jtxtGuestNameMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Sub_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Sub_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Sub_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Sub_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Sub_Bill().setVisible(true);
            }
        });
    }
    
    int xx, xy;
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCloseSubBill;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jtxtGuestId;
    private javax.swing.JTextField jtxtGuestName;
    private javax.swing.JTextField jtxtGuestName1;
    // End of variables declaration//GEN-END:variables
}
