/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JPanel;
import qlnv_gui.ConnectionDatabase;

/**
 *
 * @author thaotruogg
 */
public class MainJForm extends javax.swing.JFrame {

    /**
     * Creates new form MainJForm
     */
    public MainJForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCloseWindows = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelBill = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelProduct = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelGuest = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelPay = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jpBill = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jpBillMain = new javax.swing.JPanel();
        jpBillSub1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbBill = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jtxtSearchBill = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButtonBillDelete = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        jButtonBillAdd = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButtonBillEdit4 = new javax.swing.JButton();
        jpBillSub2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jpSubBill = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jButtonSubBillDelete = new javax.swing.JButton();
        jButtonSubBillAdd = new javax.swing.JButton();
        jButtonSubBillEdit = new javax.swing.JButton();
        jlbPay = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnBillSub1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        btnBillSub2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jpProduct = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jlName_category = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jlName_product = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jlName_provider = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnOpenCategory = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jButtonBillDelete1 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jButtonBillEdit1 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jButtonBillAdd1 = new javax.swing.JButton();
        jpGuest = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButtonBillDelete2 = new javax.swing.JButton();
        jButtonBillEdit2 = new javax.swing.JButton();
        jButtonBillAdd2 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jlName_category1 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jlName_product1 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jlName_provider1 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jtxtSearchGuest = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jpPay = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButtonBillDelete3 = new javax.swing.JButton();
        jButtonBillEdit3 = new javax.swing.JButton();
        jButtonBillAdd3 = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jtxtSearchGuest1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(233, 30, 99));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nunito ExtraBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ VẬT LIỆU XÂY DỰNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, 100));

        btnCloseWindows.setBackground(new java.awt.Color(233, 30, 99));
        btnCloseWindows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseWindowsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseWindowsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseWindowsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCloseWindowsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCloseWindowsMouseReleased(evt);
            }
        });
        btnCloseWindows.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\close_window_24px.png")); // NOI18N
        btnCloseWindows.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, -1, -1));

        jPanel1.add(btnCloseWindows, new org.netbeans.lib.awtextra.AbsoluteConstraints(1033, 0, 45, 45));

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\color.png")); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1078, 100));

        jPanel2.setBackground(new java.awt.Color(255, 64, 129));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBill.setBackground(new java.awt.Color(255, 64, 129));
        jPanelBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mousecliked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousepressed(evt);
            }
        });
        jPanelBill.setLayout(null);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\bill_24px.png")); // NOI18N
        jPanelBill.add(jLabel8);
        jLabel8.setBounds(0, 0, 60, 60);

        jLabel5.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HÓA ĐƠN");
        jPanelBill.add(jLabel5);
        jLabel5.setBounds(60, 20, 138, 20);

        jPanel2.add(jPanelBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 140, 200, 60));

        jPanelProduct.setBackground(new java.awt.Color(255, 64, 129));
        jPanelProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mousecliked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousepressed(evt);
            }
        });
        jPanelProduct.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SẢN PHẨM");
        jPanelProduct.add(jLabel2);
        jLabel2.setBounds(68, 20, 130, 20);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\product_24px.png")); // NOI18N
        jPanelProduct.add(jLabel9);
        jLabel9.setBounds(0, 0, 60, 60);

        jPanel2.add(jPanelProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 260, 200, 60));

        jPanelGuest.setBackground(new java.awt.Color(255, 64, 129));
        jPanelGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mousecliked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousepressed(evt);
            }
        });
        jPanelGuest.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("KHÁCH HÀNG");
        jPanelGuest.add(jLabel4);
        jLabel4.setBounds(60, 20, 138, 20);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\guest_male_24px.png")); // NOI18N
        jPanelGuest.add(jLabel10);
        jLabel10.setBounds(0, 0, 60, 60);

        jPanel2.add(jPanelGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 200, 200, 60));

        jPanelPay.setBackground(new java.awt.Color(255, 64, 129));
        jPanelPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mousecliked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousepressed(evt);
            }
        });
        jPanelPay.setLayout(null);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\paycheque_24px.png")); // NOI18N
        jPanelPay.add(jLabel7);
        jLabel7.setBounds(1, 0, 60, 60);

        jLabel6.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("THANH TOÁN");
        jPanelPay.add(jLabel6);
        jLabel6.setBounds(61, 0, 138, 60);

        jPanel2.add(jPanelPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 320, 200, 60));

        jLabel11.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Liu Liu");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 578, 190, 30));

        jLabel16.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Welcome back!");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("show_name_admin_here");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 100, 210, 619));

        jPanel3.setBackground(new java.awt.Color(149, 165, 166));
        jPanel3.setLayout(new java.awt.CardLayout());

        jpBill.setBackground(new java.awt.Color(232, 245, 233));
        jpBill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Nunito ExtraBold", 1, 12)); // NOI18N
        jLabel24.setText("QUẢN LÝ HÓA ĐƠN");
        jpBill.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jpBill.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 830, 10));

        jpBillMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpBillMain.setLayout(new java.awt.CardLayout());

        jpBillSub1.setBackground(new java.awt.Color(232, 245, 233));
        jpBillSub1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12423", "Dle sei", "24/02/2019"},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàng", "Ngày lập"
            }
        ));
        jtbBill.setRowHeight(24);
        jScrollPane2.setViewportView(jtbBill);

        jpBillSub1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 490, 410));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel32.setText("Ngày lập hóa đơn");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel36.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel36.setText("Mã khách hàng");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel37.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel37.setText("Tên khách hàng");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel38.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel38.setText("Mã hóa đơn");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel39.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel39.setText("23/02/2019");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel40.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel40.setText("show-here");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel41.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel41.setText("show-here");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel42.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel42.setText("show-here");
        jPanel6.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jpBillSub1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 310, 280));

        jtxtSearchBill.setBackground(new java.awt.Color(232, 245, 233));
        jtxtSearchBill.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jtxtSearchBill.setText("Nhập mã hóa đơn cần tìm");
        jtxtSearchBill.setBorder(null);
        jtxtSearchBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSearchBillMouseClicked(evt);
            }
        });
        jpBillSub1.add(jtxtSearchBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 200, 30));

        jPanel8.setBackground(new java.awt.Color(255, 64, 129));
        jpBillSub1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 10));

        jButtonBillDelete.setBackground(new java.awt.Color(244, 67, 54));
        jButtonBillDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\delete_24px.png")); // NOI18N
        jButtonBillDelete.setBorderPainted(false);
        jButtonBillDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillDeleteActionPerformed(evt);
            }
        });
        jpBillSub1.add(jButtonBillDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 80, -1));

        btnPay.setBackground(new java.awt.Color(255, 64, 129));
        btnPay.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Thanh toán");
        btnPay.setBorderPainted(false);
        btnPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        jpBillSub1.add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 100, 30));

        jButtonBillAdd.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\add_24px.png")); // NOI18N
        jButtonBillAdd.setBorderPainted(false);
        jButtonBillAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillAddActionPerformed(evt);
            }
        });
        jpBillSub1.add(jButtonBillAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jLabel46.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Xóa");
        jpBillSub1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 80, -1));

        jLabel47.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Sửa");
        jpBillSub1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, -1));

        jLabel48.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Thêm");
        jpBillSub1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jpBillSub1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 200, 12));

        jButton3.setBackground(new java.awt.Color(244, 67, 54));
        jButton3.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Tìm kiếm");
        jpBillSub1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, 30));

        jButtonBillEdit4.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillEdit4.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\edit_property_24px.png")); // NOI18N
        jButtonBillEdit4.setBorderPainted(false);
        jButtonBillEdit4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillEdit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillEdit4ActionPerformed(evt);
            }
        });
        jpBillSub1.add(jButtonBillEdit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 80, -1));

        jpBillMain.add(jpBillSub1, "card2");

        jpBillSub2.setBackground(new java.awt.Color(232, 245, 233));
        jpBillSub2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpSubBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " Số hóa đơn", "Tên sản phẩm", "Số lượng", "Đơn giá"
            }
        ));
        jpSubBill.setRowHeight(24);
        jScrollPane3.setViewportView(jpSubBill);

        jpBillSub2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 820, 410));

        jPanel9.setBackground(new java.awt.Color(255, 64, 129));
        jpBillSub2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 30, 10));

        jButtonSubBillDelete.setBackground(new java.awt.Color(244, 67, 54));
        jButtonSubBillDelete.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\delete_24px.png")); // NOI18N
        jButtonSubBillDelete.setBorderPainted(false);
        jButtonSubBillDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSubBillDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubBillDeleteActionPerformed(evt);
            }
        });
        jpBillSub2.add(jButtonSubBillDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 80, -1));

        jButtonSubBillAdd.setBackground(new java.awt.Color(255, 64, 129));
        jButtonSubBillAdd.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\add_24px.png")); // NOI18N
        jButtonSubBillAdd.setBorderPainted(false);
        jButtonSubBillAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSubBillAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubBillAddActionPerformed(evt);
            }
        });
        jpBillSub2.add(jButtonSubBillAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jButtonSubBillEdit.setBackground(new java.awt.Color(255, 64, 129));
        jButtonSubBillEdit.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\edit_property_24px.png")); // NOI18N
        jButtonSubBillEdit.setBorderPainted(false);
        jButtonSubBillEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSubBillEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubBillEditActionPerformed(evt);
            }
        });
        jpBillSub2.add(jButtonSubBillEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 80, -1));

        jlbPay.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        jlbPay.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlbPay.setText("13.000.000.000");
        jpBillSub2.add(jlbPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 100, -1));

        jLabel44.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Thêm");
        jpBillSub2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, -1));

        jLabel45.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Sửa");
        jpBillSub2.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, -1));

        jLabel54.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("VND");
        jpBillSub2.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 50, -1));

        jLabel55.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel55.setText("Tổng tiền hóa đơn:");
        jpBillSub2.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 130, -1));

        jLabel56.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Xóa");
        jpBillSub2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 80, -1));

        jpBillMain.add(jpBillSub2, "card3");

        jpBill.add(jpBillMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 840, 510));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBillSub1.setBackground(new java.awt.Color(255, 64, 129));
        btnBillSub1.setForeground(new java.awt.Color(255, 255, 255));
        btnBillSub1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBillSub1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseBillClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseBillEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseBillExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseBillPressed(evt);
            }
        });
        btnBillSub1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("HÓA ĐƠN");
        btnBillSub1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 30));

        jPanel7.add(btnBillSub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        btnBillSub2.setBackground(new java.awt.Color(216, 27, 96));
        btnBillSub2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBillSub2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseBillClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseBillEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseBillExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseBillPressed(evt);
            }
        });
        btnBillSub2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CHI TIẾT HÓA ĐƠN");
        btnBillSub2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 150, 30));

        jPanel7.add(btnBillSub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 210, 30));

        jpBill.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 400, 30));

        jPanel3.add(jpBill, "card4");

        jpProduct.setBackground(new java.awt.Color(232, 245, 233));
        jpProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Nunito ExtraBold", 1, 12)); // NOI18N
        jLabel12.setText("QUẢN LÝ SẢN PHẨM");
        jpProduct.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Số lượng tồn", "Loại", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        jpProduct.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 500, 480));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel23.setText("Loại sản phẩm");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jlName_category.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlName_category.setText("name_product");
        jPanel4.add(jlName_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel25.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel25.setText("Tên sản phẩm");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jlName_product.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlName_product.setText("name_product");
        jPanel4.add(jlName_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel27.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel27.setText("VNĐ");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel28.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel28.setText("1.000.000.000");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel29.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel29.setText("Số lượng tồn kho");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel30.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel30.setText("name_product");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel31.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel31.setText("Nhà sản xuất");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jlName_provider.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlName_provider.setText("name_product");
        jPanel4.add(jlName_provider, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel33.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel33.setText("Đơn giá");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jpProduct.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 310, 280));

        btnOpenCategory.setBackground(new java.awt.Color(244, 67, 54));
        btnOpenCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpenCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpenCategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOpenCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOpenCategoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOpenCategoryMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOpenCategoryMouseReleased(evt);
            }
        });
        btnOpenCategory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Quản lý loại vật liệu");
        btnOpenCategory.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jpProduct.add(btnOpenCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 150, 40));
        jpProduct.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 830, 10));

        jLabel21.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel21.setText("Thông tin chi tiết");
        jpProduct.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jButtonBillDelete1.setBackground(new java.awt.Color(244, 67, 54));
        jButtonBillDelete1.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\delete_24px.png")); // NOI18N
        jButtonBillDelete1.setBorderPainted(false);
        jButtonBillDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillDelete1ActionPerformed(evt);
            }
        });
        jpProduct.add(jButtonBillDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 80, -1));

        jLabel49.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Xóa");
        jpProduct.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 80, -1));

        jButtonBillEdit1.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillEdit1.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\edit_property_24px.png")); // NOI18N
        jButtonBillEdit1.setBorderPainted(false);
        jButtonBillEdit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillEdit1ActionPerformed(evt);
            }
        });
        jpProduct.add(jButtonBillEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, -1));

        jLabel50.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Sửa");
        jpProduct.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 80, -1));

        jLabel51.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Thêm");
        jpProduct.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jButtonBillAdd1.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillAdd1.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\add_24px.png")); // NOI18N
        jButtonBillAdd1.setBorderPainted(false);
        jButtonBillAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillAdd1ActionPerformed(evt);
            }
        });
        jpProduct.add(jButtonBillAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        jPanel3.add(jpProduct, "card2");

        jpGuest.setBackground(new java.awt.Color(232, 245, 233));
        jpGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Nunito ExtraBold", 1, 12)); // NOI18N
        jLabel52.setText("QUẢN LÝ KHÁCH HÀNG");
        jpGuest.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jpGuest.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 830, 10));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số điện thoại"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(24);
        jScrollPane4.setViewportView(jTable2);

        jpGuest.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 127, 500, 480));

        jButtonBillDelete2.setBackground(new java.awt.Color(244, 67, 54));
        jButtonBillDelete2.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\delete_24px.png")); // NOI18N
        jButtonBillDelete2.setBorderPainted(false);
        jButtonBillDelete2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillDelete2ActionPerformed(evt);
            }
        });
        jpGuest.add(jButtonBillDelete2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 80, -1));

        jButtonBillEdit2.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillEdit2.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\edit_property_24px.png")); // NOI18N
        jButtonBillEdit2.setBorderPainted(false);
        jButtonBillEdit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillEdit2ActionPerformed(evt);
            }
        });
        jpGuest.add(jButtonBillEdit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, -1));

        jButtonBillAdd2.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillAdd2.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\add_24px.png")); // NOI18N
        jButtonBillAdd2.setBorderPainted(false);
        jButtonBillAdd2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillAdd2ActionPerformed(evt);
            }
        });
        jpGuest.add(jButtonBillAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        jLabel57.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Thêm");
        jpGuest.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jLabel58.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Sửa");
        jpGuest.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 80, -1));

        jLabel59.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Xóa");
        jpGuest.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 80, -1));

        jLabel22.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel22.setText("Thông tin chi tiết");
        jpGuest.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel60.setText("Tên khách hàng");
        jPanel5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jlName_category1.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlName_category1.setText("name_product");
        jPanel5.add(jlName_category1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel61.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel61.setText("Mã khách hàng");
        jPanel5.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jlName_product1.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlName_product1.setText("name_product");
        jPanel5.add(jlName_product1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel62.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel62.setText("VNĐ");
        jPanel5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel63.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel63.setText("1.000.000.000");
        jPanel5.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel66.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel66.setText("Địa chỉ");
        jPanel5.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jlName_provider1.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlName_provider1.setText("name_product");
        jPanel5.add(jlName_provider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel67.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel67.setText("Nợ đầu kì");
        jPanel5.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel68.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel68.setText("Nợ cuối kì");
        jPanel5.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel69.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel69.setText("1.000.000.000");
        jPanel5.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel70.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel70.setText("VNĐ");
        jPanel5.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jpGuest.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 310, 380));

        jtxtSearchGuest.setBackground(new java.awt.Color(232, 245, 233));
        jtxtSearchGuest.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jtxtSearchGuest.setText("Nhập mã khách hàng cần tìm");
        jtxtSearchGuest.setBorder(null);
        jtxtSearchGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSearchGuestMouseClicked(evt);
            }
        });
        jtxtSearchGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSearchGuestActionPerformed(evt);
            }
        });
        jpGuest.add(jtxtSearchGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 200, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jpGuest.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 200, 12));

        jButton2.setBackground(new java.awt.Color(244, 67, 54));
        jButton2.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Tìm kiếm");
        jpGuest.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, 30));

        jPanel3.add(jpGuest, "card3");

        jpPay.setBackground(new java.awt.Color(232, 245, 233));
        jpPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Nunito ExtraBold", 1, 12)); // NOI18N
        jLabel53.setText("QUẢN LÝ THANH TOÁN");
        jpPay.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jpPay.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 830, 10));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số phiếu", "Ngày lập phiếu", "Tiền thanh toán", "Mã khách hàng"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jTable3.setRowHeight(24);
        jScrollPane5.setViewportView(jTable3);

        jpPay.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 127, 830, 480));

        jButtonBillDelete3.setBackground(new java.awt.Color(244, 67, 54));
        jButtonBillDelete3.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\delete_24px.png")); // NOI18N
        jButtonBillDelete3.setBorderPainted(false);
        jButtonBillDelete3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillDelete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillDelete3ActionPerformed(evt);
            }
        });
        jpPay.add(jButtonBillDelete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 80, -1));

        jButtonBillEdit3.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillEdit3.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\edit_property_24px.png")); // NOI18N
        jButtonBillEdit3.setBorderPainted(false);
        jButtonBillEdit3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillEdit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillEdit3ActionPerformed(evt);
            }
        });
        jpPay.add(jButtonBillEdit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, -1));

        jButtonBillAdd3.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillAdd3.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\add_24px.png")); // NOI18N
        jButtonBillAdd3.setBorderPainted(false);
        jButtonBillAdd3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillAdd3ActionPerformed(evt);
            }
        });
        jpPay.add(jButtonBillAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        jLabel64.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("Thêm");
        jpPay.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jLabel65.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Sửa");
        jpPay.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 80, -1));

        jLabel72.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("Xóa");
        jpPay.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 80, -1));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jpPay.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 200, 12));

        jtxtSearchGuest1.setBackground(new java.awt.Color(232, 245, 233));
        jtxtSearchGuest1.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jtxtSearchGuest1.setText("Nhập mã khách hàng cần tìm");
        jtxtSearchGuest1.setBorder(null);
        jtxtSearchGuest1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSearchGuest1MouseClicked(evt);
            }
        });
        jtxtSearchGuest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSearchGuest1ActionPerformed(evt);
            }
        });
        jpPay.add(jtxtSearchGuest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 200, 30));

        jButton1.setBackground(new java.awt.Color(244, 67, 54));
        jButton1.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tìm kiếm");
        jpPay.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, 30));

        jPanel3.add(jpPay, "card5");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 101, 870, 619));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseWindowsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseWindowsMouseEntered
        btnCloseWindows.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_btnCloseWindowsMouseEntered

    private void btnCloseWindowsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseWindowsMouseExited
        btnCloseWindows.setBackground(new Color(233,30,99));
    }//GEN-LAST:event_btnCloseWindowsMouseExited

    private void btnCloseWindowsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseWindowsMousePressed
        btnCloseWindows.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_btnCloseWindowsMousePressed

    private void btnCloseWindowsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseWindowsMouseReleased
        btnCloseWindows.setBackground(new Color(233,30,99));
    }//GEN-LAST:event_btnCloseWindowsMouseReleased

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btnCloseWindowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseWindowsMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseWindowsMouseClicked

    private void mousecliked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousecliked
        
        if(evt.getSource() == jPanelBill){
            jpProduct.setVisible(false);
            jpGuest.setVisible(false);
            jpBill.setVisible(true);
            jpPay.setVisible(false);
        }
        
        if(evt.getSource() == jPanelProduct){
            jpProduct.setVisible(true);
            jpGuest.setVisible(false);
            jpBill.setVisible(false);
            jpPay.setVisible(false);
        }
        
        if(evt.getSource() == jPanelGuest){
            jpProduct.setVisible(false);
            jpGuest.setVisible(true);
            jpBill.setVisible(false);
            jpPay.setVisible(false);
        }
        
        if(evt.getSource() == jPanelPay){
            jpProduct.setVisible(false);
            jpGuest.setVisible(false);
            jpBill.setVisible(false);
            jpPay.setVisible(true);
        }
    }//GEN-LAST:event_mousecliked

    
    private void mouseentered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseentered
        
        if(evt.getSource() == jPanelBill){
            setColorDeep(jPanelBill);
        }
        
        if(evt.getSource() == jPanelProduct){
            setColorDeep(jPanelProduct);
        }
        
        if(evt.getSource() == jPanelGuest){
            setColorDeep(jPanelGuest);
        }
        
        if(evt.getSource() == jPanelPay){
            setColorDeep(jPanelPay);
        }
    }//GEN-LAST:event_mouseentered

    private void mouseexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseexited
        if(evt.getSource() == jPanelBill){
            resetColor(jPanelBill); 
        }
        
        if(evt.getSource() == jPanelProduct){
            resetColor(jPanelProduct);
        }
        
        if(evt.getSource() == jPanelGuest){
            resetColor(jPanelGuest);
        }
        
        if(evt.getSource() == jPanelPay){
            resetColor(jPanelPay);
        }
    }//GEN-LAST:event_mouseexited
   
    private void mousepressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousepressed
        if(evt.getSource() == jPanelBill){
            setColor(jPanelBill);
        }
        
        if(evt.getSource() == jPanelProduct){
            setColor(jPanelProduct);
        }
        
        if(evt.getSource() == jPanelGuest){
            setColor(jPanelGuest);
        }
        
        if(evt.getSource() == jPanelPay){
            setColor(jPanelPay);
        }
    }//GEN-LAST:event_mousepressed

    private void mouseBillClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseBillClick
        if(evt.getSource() == btnBillSub1){
            jpBillSub1.setVisible(true);
            jpBillSub2.setVisible(false);
            setColorDeep(btnBillSub2);
            resetColor(btnBillSub1);
        }
        if(evt.getSource() == btnBillSub2){
            jpBillSub1.setVisible(false);
            jpBillSub2.setVisible(true);
            setColorDeep(btnBillSub1);
            resetColor(btnBillSub2);
        }
    }//GEN-LAST:event_mouseBillClick

    private void mouseBillEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseBillEntered
//        if(evt.getSource() == btnBillSub1){
//            setColorDeep(btnBillSub1);
//        }
//        
//        if(evt.getSource() == btnBillSub2){
//            setColorDeep(btnBillSub2);
//        }
    }//GEN-LAST:event_mouseBillEntered

    private void mouseBillExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseBillExited
//        if(evt.getSource() == btnBillSub1){
//            resetColor(btnBillSub1); 
//        }
//        
//        if(evt.getSource() == btnBillSub2){
//            resetColor(btnBillSub2);
//        }
    }//GEN-LAST:event_mouseBillExited

    private void mouseBillPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseBillPressed
        if(evt.getSource() == btnBillSub1){
            setColor(btnBillSub1);
        }
        
        if(evt.getSource() == btnBillSub2){
            setColor(btnBillSub2);
        }
    }//GEN-LAST:event_mouseBillPressed

    private void jButtonSubBillDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubBillDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSubBillDeleteActionPerformed

    private void jButtonSubBillAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubBillAddActionPerformed
        JFrame_Sub_Bill f = new JFrame_Sub_Bill();
        f.setVisible(true);
    }//GEN-LAST:event_jButtonSubBillAddActionPerformed

    private void jButtonSubBillEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubBillEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSubBillEditActionPerformed

    private void jButtonBillDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillDeleteActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        JFrame_Pay f = new JFrame_Pay();
        f.setVisible(true);
    }//GEN-LAST:event_btnPayActionPerformed

    private void jButtonBillAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillAddActionPerformed
        JFrame_Bill f = new JFrame_Bill();
        f.setVisible(true);
    }//GEN-LAST:event_jButtonBillAddActionPerformed

    private void jButtonBillDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillDelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillDelete1ActionPerformed

    private void jButtonBillEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillEdit1ActionPerformed
        // Đổ dữ liệu cần sửa từ table vào frame
        
        Input_Product_GUI f = new Input_Product_GUI();
        f.setVisible(true);
    }//GEN-LAST:event_jButtonBillEdit1ActionPerformed

    private void jButtonBillAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillAdd1ActionPerformed
        Input_Product_GUI f = new Input_Product_GUI();
        f.setVisible(true);
    }//GEN-LAST:event_jButtonBillAdd1ActionPerformed

    private void btnOpenCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenCategoryMouseClicked
        JFrameCategory f = new JFrameCategory();
        f.setVisible(true);
    }//GEN-LAST:event_btnOpenCategoryMouseClicked

    private void btnOpenCategoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenCategoryMousePressed
        setColorDeep(btnOpenCategory);
    }//GEN-LAST:event_btnOpenCategoryMousePressed

    private void btnOpenCategoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenCategoryMouseReleased
        setColorRed(btnOpenCategory);
    }//GEN-LAST:event_btnOpenCategoryMouseReleased

    private void btnOpenCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenCategoryMouseEntered
        setColor(btnOpenCategory);
    }//GEN-LAST:event_btnOpenCategoryMouseEntered

    private void btnOpenCategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenCategoryMouseExited
        setColorRed(btnOpenCategory);
    }//GEN-LAST:event_btnOpenCategoryMouseExited

    private void jtxtSearchBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSearchBillMouseClicked
        jtxtSearchBill.setText(null);
    }//GEN-LAST:event_jtxtSearchBillMouseClicked

    private void jButtonBillDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillDelete2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillDelete2ActionPerformed

    private void jButtonBillEdit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillEdit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillEdit2ActionPerformed

    private void jButtonBillAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillAdd2ActionPerformed
        JFrame_Input_Guest f = new JFrame_Input_Guest();
        f.setVisible(true);
    }//GEN-LAST:event_jButtonBillAdd2ActionPerformed

    private void jtxtSearchGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSearchGuestMouseClicked
        jtxtSearchGuest.setText(null);
    }//GEN-LAST:event_jtxtSearchGuestMouseClicked

    private void jtxtSearchGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSearchGuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchGuestActionPerformed

    private void jButtonBillDelete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillDelete3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillDelete3ActionPerformed

    private void jButtonBillEdit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillEdit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillEdit3ActionPerformed

    private void jButtonBillAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillAdd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillAdd3ActionPerformed

    private void jtxtSearchGuest1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSearchGuest1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchGuest1MouseClicked

    private void jtxtSearchGuest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSearchGuest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchGuest1ActionPerformed

    private void jButtonBillEdit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillEdit4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillEdit4ActionPerformed

    void setColor(JPanel jpanel){
        jpanel.setBackground(new Color(255,64,129));
    }
    
    void resetColor(JPanel jpanel){
        jpanel.setBackground(new Color(255,64,129));
    }
    
    void setColorDeep(JPanel jpanel){
        jpanel.setBackground(new Color(216, 27, 96));
    }
    
    void setColorRed(JPanel jp){
        jp.setBackground(new Color(244, 67, 54));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainJForm().setVisible(true);
        });
    }

    int xx, xy;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBillSub1;
    private javax.swing.JPanel btnBillSub2;
    private javax.swing.JPanel btnCloseWindows;
    private javax.swing.JPanel btnOpenCategory;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonBillAdd;
    private javax.swing.JButton jButtonBillAdd1;
    private javax.swing.JButton jButtonBillAdd2;
    private javax.swing.JButton jButtonBillAdd3;
    private javax.swing.JButton jButtonBillDelete;
    private javax.swing.JButton jButtonBillDelete1;
    private javax.swing.JButton jButtonBillDelete2;
    private javax.swing.JButton jButtonBillDelete3;
    private javax.swing.JButton jButtonBillEdit1;
    private javax.swing.JButton jButtonBillEdit2;
    private javax.swing.JButton jButtonBillEdit3;
    private javax.swing.JButton jButtonBillEdit4;
    private javax.swing.JButton jButtonSubBillAdd;
    private javax.swing.JButton jButtonSubBillDelete;
    private javax.swing.JButton jButtonSubBillEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBill;
    private javax.swing.JPanel jPanelGuest;
    private javax.swing.JPanel jPanelPay;
    private javax.swing.JPanel jPanelProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel jlName_category;
    private javax.swing.JLabel jlName_category1;
    private javax.swing.JLabel jlName_product;
    private javax.swing.JLabel jlName_product1;
    private javax.swing.JLabel jlName_provider;
    private javax.swing.JLabel jlName_provider1;
    private javax.swing.JLabel jlbPay;
    private javax.swing.JPanel jpBill;
    private javax.swing.JPanel jpBillMain;
    private javax.swing.JPanel jpBillSub1;
    private javax.swing.JPanel jpBillSub2;
    private javax.swing.JPanel jpGuest;
    private javax.swing.JPanel jpPay;
    private javax.swing.JPanel jpProduct;
    private javax.swing.JTable jpSubBill;
    private javax.swing.JTable jtbBill;
    private javax.swing.JTextField jtxtSearchBill;
    private javax.swing.JTextField jtxtSearchGuest;
    private javax.swing.JTextField jtxtSearchGuest1;
    // End of variables declaration//GEN-END:variables
}
