/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.ChiTietHoaDonDAL;
import DLL.HoaDonDLL;
import DLL.SanPhamDLL;
import DTO.Bill;
import DTO.Products;
import DTO.SubBill;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author thaotruogg
 */
public final class JFrame_Sub_Bill extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Sub_Bill
     */
    public JFrame_Sub_Bill() {
        initComponents();
        this.setLocationRelativeTo(null);
        BidingNameProductsToCombobox();
        BidingIdBillToCombobox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCloseSubBill = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtnSaveSubBill = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jtxtBillDonGia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinnersoLuong = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jcbxMaSP = new javax.swing.JComboBox<>();
        jcbxSoHD = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(410, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 0, 87));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HÓA ĐƠN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 0, 123, 40));

        btnCloseSubBill.setBackground(new java.awt.Color(245, 0, 87));
        btnCloseSubBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseSubBillMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseSubBillMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseSubBillMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCloseSubBillMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCloseSubBillMouseReleased(evt);
            }
        });
        btnCloseSubBill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\thaotruogg\\NetBeansProjects\\Qlnv_GUI\\assets\\close_16px.png")); // NOI18N
        btnCloseSubBill.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, -1, -1));

        jPanel1.add(btnCloseSubBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 408, 40));

        jPanel2.setBackground(new java.awt.Color(252, 228, 236));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnSaveSubBill.setBackground(new java.awt.Color(255, 64, 129));
        jbtnSaveSubBill.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jbtnSaveSubBill.setText("LƯU");
        jbtnSaveSubBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveSubBillActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSaveSubBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 80, 40));

        jLabel8.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel8.setText("Số hóa đơn");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 90, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 240, 10));

        jLabel7.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel7.setText("Đơn giá");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 100, -1));

        jtxtBillDonGia.setBackground(new java.awt.Color(252, 228, 236));
        jtxtBillDonGia.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jtxtBillDonGia.setText("10000000");
        jtxtBillDonGia.setBorder(null);
        jtxtBillDonGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBillDonGiaMouseClicked(evt);
            }
        });
        jPanel2.add(jtxtBillDonGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 200, 30));

        jLabel6.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel6.setText("Số lượng");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 100, -1));

        jLabel5.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel5.setText("VNĐ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 40, -1));

        jSpinnersoLuong.setBorder(null);
        jPanel2.add(jSpinnersoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 110, 30));

        jLabel4.setFont(new java.awt.Font("Nunito", 1, 12)); // NOI18N
        jLabel4.setText("Mã sản phẩm");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 210, 10));

        jPanel2.add(jcbxMaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 240, 30));

        jPanel2.add(jcbxSoHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 240, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 240, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 409, 319));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseSubBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSubBillMouseClicked
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCloseSubBillMouseClicked

    private void btnCloseSubBillMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSubBillMouseEntered
        btnCloseSubBill.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_btnCloseSubBillMouseEntered

    private void btnCloseSubBillMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSubBillMouseExited
        btnCloseSubBill.setBackground(new Color(245,0,87));
    }//GEN-LAST:event_btnCloseSubBillMouseExited

    private void btnCloseSubBillMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSubBillMousePressed
        btnCloseSubBill.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_btnCloseSubBillMousePressed

    private void btnCloseSubBillMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseSubBillMouseReleased
        btnCloseSubBill.setBackground(new Color(245,0,87));
    }//GEN-LAST:event_btnCloseSubBillMouseReleased

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jbtnSaveSubBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveSubBillActionPerformed
        listBill = hdDLL.getAllBill();
        int rowHD = jcbxSoHD.getSelectedIndex();
        String idHD = listBill.get(rowHD).getSoHD();
        listProducts = spDLL.getAllProducts();
        int rowSP = jcbxMaSP.getSelectedIndex();
        String idSP = listProducts.get(rowSP).getMaSP();
        int soLuong = jSpinnersoLuong.getComponentCount();
        double donGia = Double.parseDouble(jtxtBillDonGia.getText());
        
        SubBill subbill = new SubBill();
        subbill.setMaHD(idHD);
        subbill.setMaSP(idSP);
        subbill.setSoLuong(soLuong);
        subbill.setDonGia(donGia);
        if(ctDLL.AddSubBill(subbill)){
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            this.setVisible(false);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        }
    }//GEN-LAST:event_jbtnSaveSubBillActionPerformed

    private void jtxtBillDonGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBillDonGiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBillDonGiaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Sub_Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrame_Sub_Bill().setVisible(true);
        });
    }
    
    public void BidingNameProductsToCombobox(){
        listProducts = spDLL.getAllProducts();
        listProducts.forEach((product) -> {
            jcbxMaSP.addItem(product.getTenSP());
        });
    }
    
    public void BidingIdBillToCombobox(){
        listBill  = hdDLL.getAllBill();
        listBill.forEach((bill) -> {
            jcbxSoHD.addItem(bill.getSoHD());
        });
    }
    
    int xx, xy;
    
    SanPhamDLL spDLL = new SanPhamDLL();
    ArrayList<Products> listProducts = new ArrayList<>();
    
    HoaDonDLL hdDLL = new HoaDonDLL();
    ArrayList<Bill> listBill = new ArrayList<>();
    
    ChiTietHoaDonDAL ctDLL = new ChiTietHoaDonDAL();
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCloseSubBill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSpinner jSpinnersoLuong;
    private javax.swing.JButton jbtnSaveSubBill;
    private javax.swing.JComboBox<String> jcbxMaSP;
    private javax.swing.JComboBox<String> jcbxSoHD;
    private javax.swing.JTextField jtxtBillDonGia;
    // End of variables declaration//GEN-END:variables
}
