/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JPanel;
import DLL.ChiTietHoaDonDLL;
import DLL.HoaDonDLL;
import DLL.KhachHangDLL;
import DLL.SanPhamDLL;
import DTO.Bill;
import DTO.Guest;
import DTO.Products;
import DTO.SubBill;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thaotruogg
 */
public final class MainJForm extends javax.swing.JFrame {
    //Connection conn = ConnectionDatabase.getConnection();
    String queryBill = "EXEC dbo.Show_SoHoaDon";
    String querySubBill = "EXEC dbo.Show_CTHD";
    String queryGuest = "EXEC dbo.SHOW_KhachHang";
    /**
     * Creates new form MainJForm
     */
    public MainJForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        BidingHoaDon();
        BidingKhachHang();
        BidingChiTietHoaDon();
//        UpdateClass.LoadList(queryBill, jtbBill);
//        UpdateClass.LoadList(querySubBill, jtbSubBill);
//        showKhachHang();
    }
    
//    public void showKhachHang(){
//        UpdateClass.LoadList(queryGuest, jtbGuest);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCloseWindows = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelBill = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanelProduct = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelGuest = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelPay = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jpBill = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jpBillMain = new javax.swing.JPanel();
        jpBillSub1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbBill = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabelNgayHD = new javax.swing.JLabel();
        jLabelMaHD = new javax.swing.JLabel();
        jLabelMaKH = new javax.swing.JLabel();
        jLabelTenKH = new javax.swing.JLabel();
        jtxtSearchBill = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jButtonBillDelete = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        jButtonBillAdd = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jpBillSub2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbSubBill = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jButtonSubBillDelete = new javax.swing.JButton();
        jButtonSubBillAdd = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnBillSub1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        btnBillSub2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jtbnRefBill = new javax.swing.JButton();
        jpProduct = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jlName_category = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jlName_product = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jlName_provider = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnOpenCategory = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jButtonBillDelete1 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        jButtonBillEdit1 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jButtonBillAdd1 = new javax.swing.JButton();
        jpGuest = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbGuest = new javax.swing.JTable();
        jButtonGuestDelete = new javax.swing.JButton();
        jButtonBillAdd2 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jlbTenKH = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jlbMaKH = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jlbNoDauKi = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jlbDiaChi = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jlbNoCuoiKi = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jtxtSearchGuest = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jbtnRefresh = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jpPay = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButtonBillDelete3 = new javax.swing.JButton();
        jButtonBillEdit3 = new javax.swing.JButton();
        jButtonBillAdd3 = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jtxtSearchGuest1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(233, 30, 99));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nunito ExtraBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ VẬT LIỆU XÂY DỰNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, 100));

        btnCloseWindows.setBackground(new java.awt.Color(233, 30, 99));
        btnCloseWindows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseWindowsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseWindowsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseWindowsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCloseWindowsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCloseWindowsMouseReleased(evt);
            }
        });
        btnCloseWindows.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/close_window_24px.png"))); // NOI18N
        btnCloseWindows.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 11, -1, -1));

        jPanel1.add(btnCloseWindows, new org.netbeans.lib.awtextra.AbsoluteConstraints(1033, 0, 45, 45));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/color.png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1078, 100));

        jPanel2.setBackground(new java.awt.Color(255, 64, 129));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBill.setBackground(new java.awt.Color(255, 64, 129));
        jPanelBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mousecliked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousepressed(evt);
            }
        });
        jPanelBill.setLayout(null);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/paycheque_24px.png"))); // NOI18N
        jPanelBill.add(jLabel8);
        jLabel8.setBounds(0, 0, 60, 60);

        jLabel5.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HÓA ĐƠN");
        jPanelBill.add(jLabel5);
        jLabel5.setBounds(60, 20, 138, 20);

        jPanel2.add(jPanelBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 140, 200, 60));

        jPanelProduct.setBackground(new java.awt.Color(255, 64, 129));
        jPanelProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mousecliked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousepressed(evt);
            }
        });
        jPanelProduct.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SẢN PHẨM");
        jPanelProduct.add(jLabel2);
        jLabel2.setBounds(68, 20, 130, 20);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/product_24px.png"))); // NOI18N
        jPanelProduct.add(jLabel9);
        jLabel9.setBounds(0, 0, 60, 60);

        jPanel2.add(jPanelProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 260, 200, 60));

        jPanelGuest.setBackground(new java.awt.Color(255, 64, 129));
        jPanelGuest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mousecliked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousepressed(evt);
            }
        });
        jPanelGuest.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("KHÁCH HÀNG");
        jPanelGuest.add(jLabel4);
        jLabel4.setBounds(60, 20, 138, 20);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/guest_male_24px.png"))); // NOI18N
        jPanelGuest.add(jLabel10);
        jLabel10.setBounds(0, 0, 60, 60);

        jPanel2.add(jPanelGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 200, 200, 60));

        jPanelPay.setBackground(new java.awt.Color(255, 64, 129));
        jPanelPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mousecliked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseentered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseexited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mousepressed(evt);
            }
        });
        jPanelPay.setLayout(null);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/paycheque_24px.png"))); // NOI18N
        jPanelPay.add(jLabel7);
        jLabel7.setBounds(1, 0, 60, 60);

        jLabel6.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("THANH TOÁN");
        jPanelPay.add(jLabel6);
        jLabel6.setBounds(61, 0, 138, 60);

        jPanel2.add(jPanelPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 320, 200, 60));

        jLabel11.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Liu Liu");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 578, 190, 30));

        jLabel16.setFont(new java.awt.Font("Nunito", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Welcome back!");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 100, 210, 619));

        jPanel3.setBackground(new java.awt.Color(149, 165, 166));
        jPanel3.setLayout(new java.awt.CardLayout());

        jpBill.setBackground(new java.awt.Color(232, 245, 233));
        jpBill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Nunito ExtraBold", 1, 12)); // NOI18N
        jLabel24.setText("QUẢN LÝ HÓA ĐƠN");
        jpBill.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jpBill.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 830, 10));

        jpBillMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpBillMain.setLayout(new java.awt.CardLayout());

        jpBillSub1.setBackground(new java.awt.Color(232, 245, 233));
        jpBillSub1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Tên khách hàng", "Ngày lập"
            }
        ));
        jtbBill.setRowHeight(24);
        jtbBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbBillMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbBill);

        jpBillSub1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 490, 410));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel32.setText("Ngày lập hóa đơn");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel36.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel36.setText("Mã khách hàng");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel37.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel37.setText("Tên khách hàng");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel38.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel38.setText("Mã hóa đơn");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabelNgayHD.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabelNgayHD.setText("23/02/2019");
        jPanel6.add(jLabelNgayHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabelMaHD.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabelMaHD.setText("show-here");
        jPanel6.add(jLabelMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabelMaKH.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabelMaKH.setText("show-here");
        jPanel6.add(jLabelMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabelTenKH.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabelTenKH.setText("show-here");
        jPanel6.add(jLabelTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jpBillSub1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 310, 280));

        jtxtSearchBill.setBackground(new java.awt.Color(232, 245, 233));
        jtxtSearchBill.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jtxtSearchBill.setText("Nhập mã hóa đơn cần tìm");
        jtxtSearchBill.setBorder(null);
        jtxtSearchBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSearchBillMouseClicked(evt);
            }
        });
        jpBillSub1.add(jtxtSearchBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 200, 30));

        jPanel8.setBackground(new java.awt.Color(255, 64, 129));
        jpBillSub1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 10));

        jButtonBillDelete.setBackground(new java.awt.Color(244, 67, 54));
        jButtonBillDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/delete_24px.png"))); // NOI18N
        jButtonBillDelete.setBorderPainted(false);
        jButtonBillDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillDeleteActionPerformed(evt);
            }
        });
        jpBillSub1.add(jButtonBillDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 80, -1));

        btnPay.setBackground(new java.awt.Color(255, 64, 129));
        btnPay.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        btnPay.setForeground(new java.awt.Color(255, 255, 255));
        btnPay.setText("Thanh toán");
        btnPay.setBorderPainted(false);
        btnPay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        jpBillSub1.add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 100, 30));

        jButtonBillAdd.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/add_24px.png"))); // NOI18N
        jButtonBillAdd.setBorderPainted(false);
        jButtonBillAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillAddActionPerformed(evt);
            }
        });
        jpBillSub1.add(jButtonBillAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jLabel46.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Xóa");
        jpBillSub1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, -1));

        jLabel48.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("Thêm");
        jpBillSub1.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jpBillSub1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 200, 12));

        jButton5.setBackground(new java.awt.Color(244, 67, 54));
        jButton5.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Tìm kiếm");
        jpBillSub1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, 30));

        jpBillMain.add(jpBillSub1, "card2");

        jpBillSub2.setBackground(new java.awt.Color(232, 245, 233));
        jpBillSub2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbSubBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Số hóa đơn", "Tên sản phẩm", "Số lượng", "Đơn giá"
            }
        ));
        jtbSubBill.setRowHeight(24);
        jScrollPane3.setViewportView(jtbSubBill);

        jpBillSub2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 820, 410));

        jPanel9.setBackground(new java.awt.Color(255, 64, 129));
        jpBillSub2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 30, 10));

        jButtonSubBillDelete.setBackground(new java.awt.Color(244, 67, 54));
        jButtonSubBillDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/delete_24px.png"))); // NOI18N
        jButtonSubBillDelete.setBorderPainted(false);
        jButtonSubBillDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSubBillDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubBillDeleteActionPerformed(evt);
            }
        });
        jpBillSub2.add(jButtonSubBillDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 80, -1));

        jButtonSubBillAdd.setBackground(new java.awt.Color(255, 64, 129));
        jButtonSubBillAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/add_24px.png"))); // NOI18N
        jButtonSubBillAdd.setBorderPainted(false);
        jButtonSubBillAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSubBillAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubBillAddActionPerformed(evt);
            }
        });
        jpBillSub2.add(jButtonSubBillAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jLabel44.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Thêm");
        jpBillSub2.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, -1));

        jLabel56.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("Xóa");
        jpBillSub2.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, -1));

        jpBillMain.add(jpBillSub2, "card3");

        jpBill.add(jpBillMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 840, 510));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBillSub1.setBackground(new java.awt.Color(255, 64, 129));
        btnBillSub1.setForeground(new java.awt.Color(255, 255, 255));
        btnBillSub1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBillSub1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseBillClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseBillEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseBillExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseBillPressed(evt);
            }
        });
        btnBillSub1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("HÓA ĐƠN");
        btnBillSub1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 150, 30));

        jPanel7.add(btnBillSub1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 30));

        btnBillSub2.setBackground(new java.awt.Color(216, 27, 96));
        btnBillSub2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBillSub2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mouseBillClick(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseBillEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseBillExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mouseBillPressed(evt);
            }
        });
        btnBillSub2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("CHI TIẾT HÓA ĐƠN");
        btnBillSub2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 150, 30));

        jPanel7.add(btnBillSub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 210, 30));

        jpBill.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 400, 30));

        jtbnRefBill.setBackground(new java.awt.Color(244, 67, 54));
        jtbnRefBill.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jtbnRefBill.setForeground(new java.awt.Color(255, 255, 255));
        jtbnRefBill.setText("Làm mới");
        jtbnRefBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jtbnRefBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnRefBillActionPerformed(evt);
            }
        });
        jpBill.add(jtbnRefBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, 24));

        jPanel3.add(jpBill, "card4");

        jpProduct.setBackground(new java.awt.Color(232, 245, 233));
        jpProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Nunito ExtraBold", 1, 12)); // NOI18N
        jLabel12.setText("QUẢN LÝ SẢN PHẨM");
        jpProduct.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên sản phẩm", "Số lượng tồn", "Loại", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(40);
        }

        jpProduct.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 500, 480));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel23.setText("Loại sản phẩm");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jlName_category.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlName_category.setText("name_product");
        jPanel4.add(jlName_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel25.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel25.setText("Tên sản phẩm");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jlName_product.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlName_product.setText("name_product");
        jPanel4.add(jlName_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel27.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel27.setText("VNĐ");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jLabel28.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel28.setText("1.000.000.000");
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel29.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel29.setText("Số lượng tồn kho");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel30.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel30.setText("name_product");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel31.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel31.setText("Nhà sản xuất");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jlName_provider.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlName_provider.setText("name_product");
        jPanel4.add(jlName_provider, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel33.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel33.setText("Đơn giá");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jpProduct.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 310, 280));

        btnOpenCategory.setBackground(new java.awt.Color(244, 67, 54));
        btnOpenCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOpenCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOpenCategoryMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOpenCategoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOpenCategoryMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnOpenCategoryMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnOpenCategoryMouseReleased(evt);
            }
        });
        btnOpenCategory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Quản lý loại vật liệu");
        btnOpenCategory.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jpProduct.add(btnOpenCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 150, 40));
        jpProduct.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 830, 10));

        jLabel21.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel21.setText("Thông tin chi tiết");
        jpProduct.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jButtonBillDelete1.setBackground(new java.awt.Color(244, 67, 54));
        jButtonBillDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/delete_24px.png"))); // NOI18N
        jButtonBillDelete1.setBorderPainted(false);
        jButtonBillDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillDelete1ActionPerformed(evt);
            }
        });
        jpProduct.add(jButtonBillDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 80, -1));

        jLabel49.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Xóa");
        jpProduct.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 80, -1));

        jButtonBillEdit1.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/edit_property_24px.png"))); // NOI18N
        jButtonBillEdit1.setBorderPainted(false);
        jButtonBillEdit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillEdit1ActionPerformed(evt);
            }
        });
        jpProduct.add(jButtonBillEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, -1));

        jLabel50.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel50.setText("Sửa");
        jpProduct.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 80, -1));

        jLabel51.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Thêm");
        jpProduct.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jButtonBillAdd1.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/add_24px.png"))); // NOI18N
        jButtonBillAdd1.setBorderPainted(false);
        jButtonBillAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillAdd1ActionPerformed(evt);
            }
        });
        jpProduct.add(jButtonBillAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        jPanel3.add(jpProduct, "card2");

        jpGuest.setBackground(new java.awt.Color(232, 245, 233));
        jpGuest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Nunito ExtraBold", 1, 12)); // NOI18N
        jLabel52.setText("QUẢN LÝ KHÁCH HÀNG");
        jpGuest.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jpGuest.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 830, 10));

        jtbGuest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số điện thoại"
            }
        ));
        jtbGuest.setGridColor(new java.awt.Color(255, 255, 255));
        jtbGuest.setRowHeight(24);
        jtbGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbGuestMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtbGuest);

        jpGuest.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 127, 500, 480));

        jButtonGuestDelete.setBackground(new java.awt.Color(244, 67, 54));
        jButtonGuestDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/delete_24px.png"))); // NOI18N
        jButtonGuestDelete.setBorderPainted(false);
        jButtonGuestDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuestDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuestDeleteActionPerformed(evt);
            }
        });
        jpGuest.add(jButtonGuestDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, -1));

        jButtonBillAdd2.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/add_24px.png"))); // NOI18N
        jButtonBillAdd2.setBorderPainted(false);
        jButtonBillAdd2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillAdd2ActionPerformed(evt);
            }
        });
        jpGuest.add(jButtonBillAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        jLabel57.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("Thêm");
        jpGuest.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jLabel59.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel59.setText("Xóa");
        jpGuest.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 80, -1));

        jLabel22.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel22.setText("Thông tin chi tiết");
        jpGuest.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel60.setText("Tên khách hàng");
        jPanel5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jlbTenKH.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlbTenKH.setText("name_product");
        jPanel5.add(jlbTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel61.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel61.setText("Mã khách hàng");
        jPanel5.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jlbMaKH.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlbMaKH.setText("name_product");
        jPanel5.add(jlbMaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel62.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel62.setText("VNĐ");
        jPanel5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        jlbNoDauKi.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlbNoDauKi.setText("1.000.000.000");
        jPanel5.add(jlbNoDauKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 100, -1));

        jLabel66.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel66.setText("Địa chỉ");
        jPanel5.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jlbDiaChi.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlbDiaChi.setText("name_product");
        jPanel5.add(jlbDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel67.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel67.setText("Nợ đầu kì");
        jPanel5.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel68.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jLabel68.setText("Nợ cuối kì");
        jPanel5.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jlbNoCuoiKi.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jlbNoCuoiKi.setText("1.000.000.000");
        jPanel5.add(jlbNoCuoiKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 100, -1));

        jLabel70.setFont(new java.awt.Font("Nunito ExtraBold", 0, 12)); // NOI18N
        jLabel70.setText("VNĐ");
        jPanel5.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jpGuest.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 310, 380));

        jtxtSearchGuest.setBackground(new java.awt.Color(232, 245, 233));
        jtxtSearchGuest.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jtxtSearchGuest.setText("Nhập mã khách hàng cần tìm");
        jtxtSearchGuest.setBorder(null);
        jtxtSearchGuest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSearchGuestMouseClicked(evt);
            }
        });
        jtxtSearchGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSearchGuestActionPerformed(evt);
            }
        });
        jpGuest.add(jtxtSearchGuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 200, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jpGuest.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 200, 12));

        jbtnRefresh.setBackground(new java.awt.Color(244, 67, 54));
        jbtnRefresh.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jbtnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRefresh.setText("Làm mới");
        jbtnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRefreshActionPerformed(evt);
            }
        });
        jpGuest.add(jbtnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, 30));

        jButton4.setBackground(new java.awt.Color(244, 67, 54));
        jButton4.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Tìm kiếm");
        jpGuest.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, 30));

        jPanel3.add(jpGuest, "card3");

        jpPay.setBackground(new java.awt.Color(232, 245, 233));
        jpPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel53.setFont(new java.awt.Font("Nunito ExtraBold", 1, 12)); // NOI18N
        jLabel53.setText("QUẢN LÝ THANH TOÁN");
        jpPay.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jpPay.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 830, 10));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số phiếu", "Ngày lập phiếu", "Tiền thanh toán", "Mã khách hàng"
            }
        ));
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jTable3.setRowHeight(24);
        jScrollPane5.setViewportView(jTable3);

        jpPay.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 127, 830, 480));

        jButtonBillDelete3.setBackground(new java.awt.Color(244, 67, 54));
        jButtonBillDelete3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/delete_24px.png"))); // NOI18N
        jButtonBillDelete3.setBorderPainted(false);
        jButtonBillDelete3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillDelete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillDelete3ActionPerformed(evt);
            }
        });
        jpPay.add(jButtonBillDelete3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 80, -1));

        jButtonBillEdit3.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillEdit3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/edit_property_24px.png"))); // NOI18N
        jButtonBillEdit3.setBorderPainted(false);
        jButtonBillEdit3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillEdit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillEdit3ActionPerformed(evt);
            }
        });
        jpPay.add(jButtonBillEdit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 80, -1));

        jButtonBillAdd3.setBackground(new java.awt.Color(255, 64, 129));
        jButtonBillAdd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/assets/add_24px.png"))); // NOI18N
        jButtonBillAdd3.setBorderPainted(false);
        jButtonBillAdd3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBillAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBillAdd3ActionPerformed(evt);
            }
        });
        jpPay.add(jButtonBillAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        jLabel64.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("Thêm");
        jpPay.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jLabel65.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel65.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel65.setText("Sửa");
        jpPay.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 80, -1));

        jLabel72.setFont(new java.awt.Font("Nunito", 0, 12)); // NOI18N
        jLabel72.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel72.setText("Xóa");
        jpPay.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 80, -1));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jpPay.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 200, 12));

        jtxtSearchGuest1.setBackground(new java.awt.Color(232, 245, 233));
        jtxtSearchGuest1.setFont(new java.awt.Font("Nunito", 0, 14)); // NOI18N
        jtxtSearchGuest1.setText("Nhập mã khách hàng cần tìm");
        jtxtSearchGuest1.setBorder(null);
        jtxtSearchGuest1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtSearchGuest1MouseClicked(evt);
            }
        });
        jtxtSearchGuest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSearchGuest1ActionPerformed(evt);
            }
        });
        jpPay.add(jtxtSearchGuest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 200, 30));

        jButton1.setBackground(new java.awt.Color(244, 67, 54));
        jButton1.setFont(new java.awt.Font("Nunito ExtraBold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tìm kiếm");
        jpPay.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 40, -1, 30));

        jPanel3.add(jpPay, "card5");

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 101, 870, 619));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseWindowsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseWindowsMouseEntered
        btnCloseWindows.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_btnCloseWindowsMouseEntered

    private void btnCloseWindowsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseWindowsMouseExited
        btnCloseWindows.setBackground(new Color(233,30,99));
    }//GEN-LAST:event_btnCloseWindowsMouseExited

    private void btnCloseWindowsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseWindowsMousePressed
        btnCloseWindows.setBackground(new Color(244, 67, 54));
    }//GEN-LAST:event_btnCloseWindowsMousePressed

    private void btnCloseWindowsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseWindowsMouseReleased
        btnCloseWindows.setBackground(new Color(233,30,99));
    }//GEN-LAST:event_btnCloseWindowsMouseReleased

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btnCloseWindowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseWindowsMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseWindowsMouseClicked

    private void mousecliked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousecliked
        
        if(evt.getSource() == jPanelBill){
            jpProduct.setVisible(false);
            jpGuest.setVisible(false);
            jpBill.setVisible(true);
            jpPay.setVisible(false);
        }
        
        if(evt.getSource() == jPanelProduct){
            jpProduct.setVisible(true);
            jpGuest.setVisible(false);
            jpBill.setVisible(false);
            jpPay.setVisible(false);
        }
        
        if(evt.getSource() == jPanelGuest){
            jpProduct.setVisible(false);
            jpGuest.setVisible(true);
            jpBill.setVisible(false);
            jpPay.setVisible(false);
        }
        
        if(evt.getSource() == jPanelPay){
            jpProduct.setVisible(false);
            jpGuest.setVisible(false);
            jpBill.setVisible(false);
            jpPay.setVisible(true);
        }
    }//GEN-LAST:event_mousecliked

    
    private void mouseentered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseentered
        
        if(evt.getSource() == jPanelBill){
            setColorDeep(jPanelBill);
        }
        
        if(evt.getSource() == jPanelProduct){
            setColorDeep(jPanelProduct);
        }
        
        if(evt.getSource() == jPanelGuest){
            setColorDeep(jPanelGuest);
        }
        
        if(evt.getSource() == jPanelPay){
            setColorDeep(jPanelPay);
        }
    }//GEN-LAST:event_mouseentered

    private void mouseexited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseexited
        if(evt.getSource() == jPanelBill){
            resetColor(jPanelBill); 
        }
        
        if(evt.getSource() == jPanelProduct){
            resetColor(jPanelProduct);
        }
        
        if(evt.getSource() == jPanelGuest){
            resetColor(jPanelGuest);
        }
        
        if(evt.getSource() == jPanelPay){
            resetColor(jPanelPay);
        }
    }//GEN-LAST:event_mouseexited
   
    private void mousepressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mousepressed
        if(evt.getSource() == jPanelBill){
            setColor(jPanelBill);
        }
        
        if(evt.getSource() == jPanelProduct){
            setColor(jPanelProduct);
        }
        
        if(evt.getSource() == jPanelGuest){
            setColor(jPanelGuest);
        }
        
        if(evt.getSource() == jPanelPay){
            setColor(jPanelPay);
        }
    }//GEN-LAST:event_mousepressed

    private void mouseBillClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseBillClick
        if(evt.getSource() == btnBillSub1){
            jpBillSub1.setVisible(true);
            jpBillSub2.setVisible(false);
            setColorDeep(btnBillSub2);
            resetColor(btnBillSub1);
        }
        if(evt.getSource() == btnBillSub2){
            jpBillSub1.setVisible(false);
            jpBillSub2.setVisible(true);
            setColorDeep(btnBillSub1);
            resetColor(btnBillSub2);
        }
    }//GEN-LAST:event_mouseBillClick

    private void mouseBillEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseBillEntered
//        
    }//GEN-LAST:event_mouseBillEntered

    private void mouseBillExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseBillExited
//        
    }//GEN-LAST:event_mouseBillExited

    private void mouseBillPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseBillPressed
        if(evt.getSource() == btnBillSub1){
            setColor(btnBillSub1);
        }
        
        if(evt.getSource() == btnBillSub2){
            setColor(btnBillSub2);
        }
    }//GEN-LAST:event_mouseBillPressed

    private void jButtonSubBillDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubBillDeleteActionPerformed
        if(jtbSubBill.getSelectedRow() != -1){
            int row =jtbSubBill.getSelectedRow();
            listSubBill = cthdDLL.getAllSubBill();
            if(cthdDLL.DeleteBill(listSubBill.get(row).getMaHD())){
                JOptionPane.showMessageDialog(this, "Xoa hoa don thanh cong!");
                BidingChiTietHoaDon();
            }
            else{
                JOptionPane.showMessageDialog(this, "Xoa hoa don that bai!");
            }
        }
    }//GEN-LAST:event_jButtonSubBillDeleteActionPerformed

    private void jButtonSubBillAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubBillAddActionPerformed
        JFrame_Sub_Bill f = new JFrame_Sub_Bill();
        f.setVisible(true);
    }//GEN-LAST:event_jButtonSubBillAddActionPerformed

    private void jButtonBillDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillDeleteActionPerformed
        if(jtbBill.getSelectedRow() != -1){
            int row =jtbBill.getSelectedRow();
            listBill = hdDLL.getAllBill();
            if(hdDLL.DeleteBill(listBill.get(row).getSoHD())){
                JOptionPane.showMessageDialog(this, "Xoa hoa don thanh cong!");
                BidingHoaDon();
                BidingChiTietHoaDon();
            }
            else{
                JOptionPane.showMessageDialog(this, "Xoa hoa don that bai!");
            }
        }
    }//GEN-LAST:event_jButtonBillDeleteActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        JFrame_Pay f = new JFrame_Pay();
        f.setVisible(true);
    }//GEN-LAST:event_btnPayActionPerformed

    private void jButtonBillAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillAddActionPerformed
        JFrame_Bill f = new JFrame_Bill();
        f.setVisible(true);
    }//GEN-LAST:event_jButtonBillAddActionPerformed

    private void jButtonBillDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillDelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillDelete1ActionPerformed

    private void jButtonBillEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillEdit1ActionPerformed
        // Đổ dữ liệu cần sửa từ table vào frame
        
        Input_Product_GUI f = new Input_Product_GUI();
        f.setVisible(true);
    }//GEN-LAST:event_jButtonBillEdit1ActionPerformed

    private void jButtonBillAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillAdd1ActionPerformed
        Input_Product_GUI f = new Input_Product_GUI();
        f.setVisible(true);
    }//GEN-LAST:event_jButtonBillAdd1ActionPerformed

    private void btnOpenCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenCategoryMouseClicked
        JFrameCategory f = new JFrameCategory();
        f.setVisible(true);
    }//GEN-LAST:event_btnOpenCategoryMouseClicked

    private void btnOpenCategoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenCategoryMousePressed
        setColorDeep(btnOpenCategory);
    }//GEN-LAST:event_btnOpenCategoryMousePressed

    private void btnOpenCategoryMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenCategoryMouseReleased
        setColorRed(btnOpenCategory);
    }//GEN-LAST:event_btnOpenCategoryMouseReleased

    private void btnOpenCategoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenCategoryMouseEntered
        setColor(btnOpenCategory);
    }//GEN-LAST:event_btnOpenCategoryMouseEntered

    private void btnOpenCategoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOpenCategoryMouseExited
        setColorRed(btnOpenCategory);
    }//GEN-LAST:event_btnOpenCategoryMouseExited

    private void jtxtSearchBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSearchBillMouseClicked
        jtxtSearchBill.setText(null);
    }//GEN-LAST:event_jtxtSearchBillMouseClicked

    private void jButtonGuestDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuestDeleteActionPerformed
        if(jtbGuest.getSelectedRow() != -1){
            int row =jtbGuest.getSelectedRow();
            listGuest = khDLL.getAllKhachHang();
            if(khDLL.DeleteGuest(listGuest.get(row).getMaKH())){
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                BidingKhachHang();
            }
            else{
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }//GEN-LAST:event_jButtonGuestDeleteActionPerformed

    private void jButtonBillAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillAdd2ActionPerformed
        JFrame_Input_Guest f = new JFrame_Input_Guest();
        f.setVisible(true);
    }//GEN-LAST:event_jButtonBillAdd2ActionPerformed

    private void jtxtSearchGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSearchGuestMouseClicked
        jtxtSearchGuest.setText(null);
    }//GEN-LAST:event_jtxtSearchGuestMouseClicked

    private void jtxtSearchGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSearchGuestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchGuestActionPerformed

    private void jButtonBillDelete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillDelete3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillDelete3ActionPerformed

    private void jButtonBillEdit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillEdit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillEdit3ActionPerformed

    private void jButtonBillAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBillAdd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBillAdd3ActionPerformed

    private void jtxtSearchGuest1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtSearchGuest1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchGuest1MouseClicked

    private void jtxtSearchGuest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSearchGuest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSearchGuest1ActionPerformed

    private void jtbBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbBillMouseClicked
        
    }//GEN-LAST:event_jtbBillMouseClicked

    private void jtbGuestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbGuestMouseClicked
        int row = jtbGuest.getSelectedRow();
        listGuest = khDLL.getAllKhachHang();
        jlbMaKH.setText(listGuest.get(row).getMaKH());
        jlbTenKH.setText(listGuest.get(row).getTenKH());
        jlbNoDauKi.setText(Double.toString(listGuest.get(row).getNoDK()));
        jlbNoCuoiKi.setText(Double.toString(listGuest.get(row).getNoCK()));
        jlbDiaChi.setText(listGuest.get(row).getDiaChi());
    }//GEN-LAST:event_jtbGuestMouseClicked

    private void jbtnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRefreshActionPerformed
        BidingKhachHang();
    }//GEN-LAST:event_jbtnRefreshActionPerformed

    private void jtbnRefBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnRefBillActionPerformed
        BidingHoaDon();
        BidingChiTietHoaDon();
    }//GEN-LAST:event_jtbnRefBillActionPerformed

    void setColor(JPanel jpanel){
        jpanel.setBackground(new Color(255,64,129));
    }
    
    void resetColor(JPanel jpanel){
        jpanel.setBackground(new Color(255,64,129));
    }
    
    void setColorDeep(JPanel jpanel){
        jpanel.setBackground(new Color(216, 27, 96));
    }
    
    void setColorRed(JPanel jp){
        jp.setBackground(new Color(244, 67, 54));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        
        java.awt.EventQueue.invokeLater(() -> {
            new MainJForm().setVisible(true);
        });
    }
    
    public void BidingHoaDon(){
        listBill = hdDLL.getAllBill();
        Vector columns = new Vector();
        columns.add("Mã hóa đơn");
        columns.add("Tên khách hàng");
        columns.add("Ngày hóa đơn");
        
        Vector data = new Vector();
        listBill.stream().map((bill) -> {
            Vector row = new Vector();
            row.add(bill.getSoHD());
            listGuest = khDLL.getById(bill.getMaKH());
            row.add(listGuest.get(0).getTenKH());
            row.add(bill.getNgayHD());
            return row;
        }).forEachOrdered((row) -> {
            data.add(row);
        });
        DefaultTableModel model = new DefaultTableModel(data, columns);
        jtbBill.setModel(model);
    }
    
    public void BidingKhachHang(){
        listGuest = khDLL.getAllKhachHang();
        Vector columns = new Vector();
        columns.add("Mã khách hàng");
        columns.add("Tên khách hàng");
        columns.add("Số điện thoại");
        
        Vector data = new Vector();
        listGuest.stream().map((guest) -> {
            Vector row = new Vector();
            row.add(guest.getMaKH());
            row.add(guest.getTenKH());
            row.add(guest.getSdt());
            return row;
        }).forEachOrdered((row) -> {
            data.add(row);
        });
        DefaultTableModel model = new DefaultTableModel(data, columns);
        jtbGuest.setModel(model);
    }

    public void BidingChiTietHoaDon(){
        listSubBill = cthdDLL.getAllSubBill();
        Vector columns = new Vector();
        columns.add("Mã hóa đơn");
        columns.add("Tên sản phẩm");
        columns.add("Số lượng");
        columns.add("Đơn giá");
        
        Vector data = new Vector();
        listSubBill.stream().map((subBill) -> {
            Vector rows = new Vector();
            rows.add(subBill.getMaHD());
            listProduct = spDLL.getById(subBill.getMaSP());
            rows.add(listProduct.get(0).getTenSP());
            rows.add(subBill.getSoLuong());
            rows.add(subBill.getDonGia());
            return rows;
        }).forEachOrdered((rows) -> {
            data.add(rows);
        });
        DefaultTableModel model = new DefaultTableModel(data, columns);
        jtbSubBill.setModel(model);
    }
    
    int xx, xy;
    String maHDTemp;
    
    KhachHangDLL khDLL = new KhachHangDLL();
    ArrayList<Guest> listGuest = new ArrayList<>();
    
    HoaDonDLL hdDLL = new HoaDonDLL();
    ArrayList<Bill> listBill = new ArrayList<>();
    
    ChiTietHoaDonDLL cthdDLL = new ChiTietHoaDonDLL();
    ArrayList<SubBill> listSubBill = new ArrayList<>();
    
    SanPhamDLL spDLL = new SanPhamDLL();
    ArrayList<Products> listProduct = new ArrayList<>();
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBillSub1;
    private javax.swing.JPanel btnBillSub2;
    private javax.swing.JPanel btnCloseWindows;
    private javax.swing.JPanel btnOpenCategory;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonBillAdd;
    private javax.swing.JButton jButtonBillAdd1;
    private javax.swing.JButton jButtonBillAdd2;
    private javax.swing.JButton jButtonBillAdd3;
    private javax.swing.JButton jButtonBillDelete;
    private javax.swing.JButton jButtonBillDelete1;
    private javax.swing.JButton jButtonBillDelete3;
    private javax.swing.JButton jButtonBillEdit1;
    private javax.swing.JButton jButtonBillEdit3;
    private javax.swing.JButton jButtonGuestDelete;
    private javax.swing.JButton jButtonSubBillAdd;
    private javax.swing.JButton jButtonSubBillDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMaHD;
    private javax.swing.JLabel jLabelMaKH;
    private javax.swing.JLabel jLabelNgayHD;
    private javax.swing.JLabel jLabelTenKH;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelBill;
    private javax.swing.JPanel jPanelGuest;
    private javax.swing.JPanel jPanelPay;
    private javax.swing.JPanel jPanelProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton jbtnRefresh;
    private javax.swing.JLabel jlName_category;
    private javax.swing.JLabel jlName_product;
    private javax.swing.JLabel jlName_provider;
    private javax.swing.JLabel jlbDiaChi;
    private javax.swing.JLabel jlbMaKH;
    private javax.swing.JLabel jlbNoCuoiKi;
    private javax.swing.JLabel jlbNoDauKi;
    private javax.swing.JLabel jlbTenKH;
    private javax.swing.JPanel jpBill;
    private javax.swing.JPanel jpBillMain;
    private javax.swing.JPanel jpBillSub1;
    private javax.swing.JPanel jpBillSub2;
    private javax.swing.JPanel jpGuest;
    private javax.swing.JPanel jpPay;
    private javax.swing.JPanel jpProduct;
    private javax.swing.JTable jtbBill;
    private javax.swing.JTable jtbGuest;
    private javax.swing.JTable jtbSubBill;
    private javax.swing.JButton jtbnRefBill;
    private javax.swing.JTextField jtxtSearchBill;
    private javax.swing.JTextField jtxtSearchGuest;
    private javax.swing.JTextField jtxtSearchGuest1;
    // End of variables declaration//GEN-END:variables
}
